### ISSUE TITLE
To Do List (large scale)

### ISSUE THREAD

**Issue by BOberreither** [semantic-kraus/lk-data#65]
# Milestones to finalize the data
## Enrich Data
- [x] Add Fackel-Identifiers to listfackel.xml
see https://github.com/semantic-kraus/lk-data/issues/66
### Data
- [x] listWork.xml: Identifiers (xml:id and  pmb URL)
see https://github.com/semantic-kraus/lk-data/issues/68
- [x] Intertextual Relations: `quote[starts-with(@source, "https://fackel")]` - awaiting https://github.com/semantic-kraus/lk-data/issues/66
- [x] Intertextual Relations: `note[@type="intertext"]` - awaiting https://github.com/semantic-kraus/lk-data/issues/66
- [ ] Intertextual Relations: `rs[@subtype="fackel"]`
### Metadata
- [ ] Add data provenance to entire lk-graph

## File Formats
- [ ] change all output file formats to .trig
